### ISSUE TITLE
Inventory Bug + Multiples Canoes

### ISSUE THREAD

**Issue by ToniSevHD** [RexShack/rsg_canoe#1]
When you take the canoe out, you sail, you leave it on the shore. The inventory stops working. And by resetting the inventory to fix it, I can get loads of canoes without limit.

**Comment by RexShack** [comment]
struggling to understand how the inventory stops working

**Comment by ToniSevHD** [comment]
[   1181641] [b1436_GTAProce]             MainThrd/ ^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export GetPlate in resource qbr-core^7

**Comment by RexShack** [comment]
that has nothing do do with the rsg_canoe script as that is not even called

**Comment by ToniSevHD** [comment]
The default game, if it detects that you are in the water, does not allow you to use or tonics or anything to recover stamina and not drown. Perhaps it is something like that, that is linked to the fact that the player cannot interact with anything in the water and being in the canoe works the same.

**Comment by ToniSevHD** [comment]
Another thing to look into is that you can take out as many canoes as you want if you assign them to a quick access (1-6).

**Comment by ToniSevHD** [comment]
![image](https://user-images.githubusercontent.com/83134630/172363842-453359f1-1686-437b-983a-dbaf5a20da84.png)

**Comment by RexShack** [comment]
rgr understand that and will make it so the deployed canoe is deleted on use

**Comment by RexShack** [comment]
canoe will be now be deleted on deployment

**Comment by ToniSevHD** [comment]
If I just tried it and it disappears from the inventory. Great Work!
Is there any chance of getting it back? Or would it stay there for anyone who passes by?

**Comment by ToniSevHD** [comment]
Ok, i test with last update of QBR-Core and work fine inventory. You need update the last QBR-Core and QBR-Inventory and work. Can you test it to confirm?
